const localizedStrings = {
    en: {
      profile: {
        contact: "Contact",
        about: "About",
        badges: "Badges",
        editProfile: "Edit Profile",
        currentRank: "Current Rank",
        lockedBadges: "Locked Badges",
        email: "Email",
        personalEmail: "Personal Email",
        contactNumber: "Contact Number",
        facebook: "Facebook",
        linkedin: "Linkedin",
        skype: "Skype",
        uploadPhoto: "Upload Photo ",
        editProfilePic: "Edit Profile Picture",
        uploadProfilePic: " + Upload Profile Picture",
        max: "max",
        personalInfo: "Personal Information",
        nickname: "Nickname",
        bio: "Bio",
        phoneNumber: "Phone Number",
      },
      notifications: {
        notifications: "Notifications",
        unread: "Unread",
        read: "Read",
        markAllAsRead: "Mark All as Read",
      },
      gigs: {
        gigs: "Gigs",
        availableGigs: "Available",
        acceptedGigs: "Accepted",
        ongoingGigs: "Ongoing",
        closedGigs: "Closed",
        createGig: "Create",
        newGig: "New Gig",
        completedGigs: "Completed",
        updateGig: "Update",
        title: "Gig Title",
        description: "Description",
        skills: "Skills",
        gigType: "Gig Type",
        location: "Location",
        startDate: "Start Date",
        startTime: "Start Time",
        endDate: "End Date",
        endTime: "End Time",
        date: "Date",
        gigInformation: 'Gig Information',
        supervisor: 'Supervisor',
        assignedEngineer: 'Assigned Engineer',
        email: 'Email',
        timeline: 'Timeline',
        feedback: 'Feedback'
      },
      locations: {
        locationList: "Location List",
        viewMap: "View Map",
        createLocation: "Create Location",
        updateLocation: "Update Location",
        editLocation: "Edit Location",
        deleteLocation: "Delete Location",
        locationDetails: 'Location Details',
        information: 'Information',
        contact: 'Contact',
        supervisor: 'Supervisor',
        engineersStationed: 'Engineers Stationed',
        pastGigCompletion: 'Past Gig Completion',
        location: 'Location'
      },
      people: {
        people: "People",
        availableEngineers: "Available Engineers",
        leaves: "Absence"
      },
      home: {
        home: "Home",
        yourActivities: "Progress this week",
        thisWeek: 'This week: ',
        lastWeek: 'Last week: ',
        userTrend: 'Since last week',
        companyTrend: 'Company trend',
        completed: 'Completed',
        earned: 'Earned',
        newQuest: "New Quest",
        whatsNext: "What's Next",
        yourProfile: "Your Profile",
        bannerHeader1: "Last week you're on a streak, ",
        bannerDesc:"Last week, you have completed <b>{goalsCount}</b> of your goals and <b>{questsCount}</b> quests. You have also earned over <b>{pointsCount}EP</b>. Let's do better this week.",
        bannerDescQuestAclOff:"Last week, you have completed <b>{goalsCount}</b> of your goals. You have also earned over <b>{pointsCount}EP</b>. Let's do better this week.",
        bannerDescLeft1: "Last week, you have completed",
        bannerDescMid1: "of your goals and",
        bannerDescRight1: "quests. You have also earned over",
        bannerDescRightEnd1: "Let's do better this week",
        bannerHeader2: "Welcome ",
        bannerDesc2:
          "Hope you are refreshed for a new week of productivity. Lets start by setting your goals and completing quests to earn points.",
        bannerDesc2QuestAclOff:
          "Hope you are refreshed for a new week of productivity. Lets start by setting your goals to earn points.",
      },
      quest: {
        quests: 'Quests',
        quest: "Quest",
        ongoing: "Ongoing",
        completed: "Completed",
        moderator: "Moderator",
        points: "Points",
        done: "Done",
        status: "Status",
        submission: "Submission",
        reject: "Reject",
        approve: "Approve",
        badge: "Badge",
        timeLeft: "Time Left",
        created: "Created",
        started: "Started",
        emptyQuest: "Looks like there’s no quest available yet",
        bannerHeader: "Advance Yourself by Earning Recognition Points. Help Others Rise with You!",
        bannerDescLeft: "Conquer quests and compete with your team! You have <b>",
        bannerDescMid: "</b> ongoing ",
        admin: 'Admin',
        details: 'Details',
        action: 'Action',
        reward: 'Reward',
        recipient: 'Recipient',
        review: 'Review',
        completeQuestAction: 'Complete Quest Action',
        setCustomRules: 'Set Custom Rules',
        modarator: 'Modarator',
        taskDescription: 'Task Description',
        hint: 'Hint',
        rewardType: 'Reward Type',
        value: 'Value',
        questTitle: 'Quest Title',
        questDescription: 'Description',
        skills: 'Skills',
        category: 'Category',
        activePeriod: 'Active Period',
        startDate: 'Start Date',
        endDate: 'End Date',
        expirationPolicy: 'This quest does not have an expiration date.',
        questTitlePlaceholder: 'Give a name to your quest',
        descriptionPlaceholder: 'Give a description to your quest',
        categoryPlaceholder: 'Choose your quest category',
        recipientHeader: 'Set up the requirements',
      },
      leaderboard: {
        leaderboard: "Leaderboard",
        overall: "Overall",
        team: "Team",
        bannerHeader: "Collect points and challenge your colleagues",
        bannerDesc:
          "Track your earned points and see where you stand among your colleagues. Challenge them for the",
        bannerDescRight: "spot every week",
        weekly: "Weekly",
        monthly: "Monthly",
        allTime: "All Time",
        myStanding: "My Standing",
        emptyPoints: "Looks like there’s nothing available yet",
        previousWeek: "Previous Week",
      },
      myPoints: {
        rewardedBy: "Rewarded By",
        badge: "Badge",
        redemptionItem: "Redemption Item",
        points: "Points",
        myPoints: "My Points",
        currentPoints: "Current Points",
        spent: "Spent",
        pending: "Pending",
        totalPoints: "Total Points",
        type: "Type",
        awardedBy: "Awarded By",
        emptyPoints: "Earn points to redeem rewards and get achievements"
      },
      redemption: {
        emptyHistoryRewards: "Looks like there’s no items in your history yet",
        redemptionInfo: "Redemption Info",
        description: "Description",
        redemption: "Redemption",
        featured: "Featured",
        history: "History",
        wishlist: "Wishlist",
        bannerHeader: "Reward Yourself",
        bannerDesc:
          "We have amazing items for you to redeem with points you earn from completing Quests and Goals.",
        categories: "Categories",
        seeAll: "See All",
        emptyRewards: "Looks like there’s no rewards yet",
        justForYou: "Just For You",
        topRewards: "Top Rewards",
        redemptionInfo: "Redemption Info",
        status: "Status",
        expiringOn: "Expiring on",
        Redeem: "redeem",
        emptyWishlistRewards: "Looks there’s no items in your wishlist yet",
      },
      approveGoal: {
        alertTitle: "Approve Goal",
        alertbody: "Acknowledge the completion of ",
        goal: "goal",
        approve: "Approve",
      },
      completeGoal: {
        alertTitle: "Complete Goal",
        alertbody: "Are you sure that you want to complete this goal?",
        submit: "Submit",
      },
      deleteGoal: {
        alertTitle: "Delete Goal",
        alertbody: "Are you sure that you want to delete this goal?",
        delete: "Delete",
      },
      rejectGoal: {
        alertTitle: "Reject Goal",
        alertbodyleft: "Something wrong with ",
        alertbodyright: " goal? What's the reason?",
        reject: "Reject",
      },
      submitGoal: {
        alertTitle: "Submit Goal",
        alertbody:
          "By submitting this goal, all task will be completed and submitted for review by ",
        submit: "Submit",
      },
      lazyLoading: {
        suspense: "I am working on it ...",
      },
      logoutDialog: {
        modalTitle: "We will miss you",
        modalBody: "Are you sure you want proceed?",
        modalFooter: "Go back",
        continue: "Continue",
      },
      sideNavBar: {
        logoText: "SelfDrvn",
        admin: "Admin",
        goalSetting: "Goal Setting",
        reward: "Reward",
        locations: "Locations",
        gigs: "Gigs",
        people: "People",
        quest: "Quests",
        goalSetting: "Goals",
        quiz: "Quiz",
        reward: "Rewards",
        organization: "Organization",
        info: "Info",
        rmDashboard: "Dashboard",
        GigArenaHeader: "GigArena"
      },
      notFound: {
        topText: "This page does not exist.",
        bottomText:
          "We looked everywhere for this page.Are you sure the website URL is correct? Get in touch with our support team for help.",
      },
      goalSetting: {
        goals: 'Goals',
        goalSetting: "Goal Setting",
        yourGoals: "Your Goals",
        editGoal: "Edit Goal",
        newGoal: "New Goal",
        targeting: "What is the Key Result You are Targeting?",
        goalAlignment: "Goal Alignment",
        addTask: "Add Task",
        reviewee: "Reviewee",
        maxDateMessage: "Date for Remind Me should not be later than due date",
        task: "Task",
        taskName: "Task Name",
        deleteTheTask: "Delete the Task",
        dueDate: "Due Date",
        remindMe: "Remind Me (Optional)",
        strin: "strin",
        updateGoal: "Update Goal",
        startGoal: "Start Goal",
        emptyGoals:
          "Looks like there’s no goals yet, you can start by adding one right now",
        deleteGoal: "Delete Goal",
        reviewer: "Reviewer",
        reject: "Reject",
        approve: "Approve",
        sGoal: "'s Goal",
        selectGoalAlignments: "Select Goal Alignments",
        teamGoals: "Team Goal",
        bannerHeader: "Move forward as a team towards company goals",
        bannerDesc: "Each Goal is designed to help you and your company grow together. Complete as many as you can!",
        hasNotStarted: "Has not started",
        ongoing: "Ongoing",
        pendingReview: "Pending Review",
        completed: "Completed",
        submitForReview: "Submit for review",
        completeGoal: "Complete Goal",
        noGoals: "No Goals",
        goalStatus: "Goal Status",
        addNewGoal: "Add New Goal",
        teamMembers: "Team Members",
        selectReviewee: "Select Reviewee",
        selectReviewer: "Select Reviewer",
        goalNotFound: "Goal Not Found.",
        goalOwner: "Goal owner",
      },
      rmDashboard : {
        overViewTab: "Overview",
        LeaveTab: "Leaves",
        ExportDataButton: "Export Data",
        CurrentDayAction: "Current day actions",
        EngineersOnLeave: "Engineers on leave",
        EngineersWhoAreLate: "Engineers who are late",
        ListOfGigsOpenToday: "List of gigs open today",
        ListOfAvailableReplacementEngineers: "List of available replacement engineers",
        ListOfEngineersAppliedLeaveForNext5Days: "List of engineers applied leave for next 5 days", 
      },
      quiz: {
        bannerHeader: "Quiz",
        all: "All",
        ongoing: "Ongoing",
        expired: "Expired",
        completed: "Completed",
        published:"Published",
        drafts: "Drafts",
        admin: "Admin",
        user:"User",
        quiz:"Quiz",
        quizes:"Quizes",
        addNewQuiz:"Add New Quiz",
        republishQuiz:"Republish Quiz",
        republish: "Republish",
        exportData:"Export Data",
        admin: "Admin",
        timeLeft: "Time Left",
        edit:"Edit",
        unpublishQuiz:"Unpublish Quiz",
        addParticipants:"Add Participants",
        export:"Export",
        shareLink:"Share Link",
        publishedResponses: "How well you know your company?",
        users:"Users",
        sentOn:"Sent on",
        responded:"Responded",
        pending:"Pending",
        score:"Score",
        hasNotResponded:"Has not responded",
        title: "Quiz Title",
        titlePlaceholder:"Enter quiz title here",
        description:"Quiz Description",
        descriptionPlaceHolder:"Enter quiz description here",
        quit:"Quit",
        publish:"Publish",
        saveAsDraft:"Save As Draft",
        details:"Details",
        settings:"Question Settings",
        switch:"Randomize options order",
        randomize:"Randomize the order of the answers shown in each question",
        question:"Question ",
        score:"Score  ",
        scoreInfo:"Please assign score according to the difficulty of the question",
        multipleChoice:"Multiple Choice",
        singleChoice:"Single Choice",
        nextQuestion:"+ Next Question",
        remove:"Remove",
        rightAnswerInfo:"Add Right Answer Text",
        wrongAnswerInfo:"Add Wrong Answer Text",
        addOption: "+ Add Option",
        questionGraphic: "Question Graphic",
        addQuestionGraphic:"Add Question Graphic",
        remove:"Remove",
        description: "Description",
        quizMe: "Quiz Me!",
        completedQuiz: "Completed - See Result",
        ongoigQuizAnswered: "people have already completed this quiz",
        completedQuizAnswered: "people have already answered this quiz",
        expiredQuizAnswered: "You did not respond to this quiz",
        isCorrectMsg:"Well done!",
        wrongAnswerMsg: "Oops, that's not quite correct. No worries, you'll get it on the next try.",
        submitQuiz:"Submit Quiz",
        selectMoreText:"select more than one answer",
        question: "Question",
        confirm: "Confirm",
        confirmText: "Are you sure?",
        confirmSubtext: "You cannot retake this quiz after you have viewed the answers",
        confirmSubheader: "Do you want to quit the page?",
        discardText: "Do you want to discard the quiz?",
        publishEditText: "Are you sure you want to continue?",
        publishEditSubtext: "The users response will be reset",
        days: "Days",
        youCompleted: "You’ve Completed",
        attemptsLeft: "Attempts Left",
        retakeQuiz: "Retake Quiz",
        viewAnswers: "View Answer",
        quizInvitation: "Quiz Invitation",
        respondents: "Respondents",
        subject: "Subject",
        message: "Message",
        publishDate: "Publish Date",
        expiryDate: "Expiry Date",
        optional: "Optional",
        expiredNotificationText: "Oops, you miss it.",
        expiredNotificationSubText: "This quiz has expired.",
        remindUsersBy: "Remind Users by",
        numberOfAttempts: "Number of Attempts",
        addNewQuest: "Add to a new quest",
        back: "Back",
        quizInvitationInfo:"Creates a new quest with this quiz as one of it’s quest actions",
        dateText: "Date is according to GMT+8",
        daysSubmission: "Days Before Submission",
        selectQuizToRepublish:"Select quiz to republish",
        everyone: "Everyone",
        yes:"Yes",
        remindLabel: "Days remaning until due date",
        unlimitedAttemptsLabel: "0 = unlimited attempts",
        dateRangeText: "Apply",
        quizBannerDesc:"Hey, you found the Quiz page! While you’re here, explore the quizzes that catch your interest, and give them a shot to learn more about the topic. The more quizzes you beat, the more points you earn to redeem more rewards :)",
      },
      feedback:{
        feedback: 'Feedback',
        overview: 'Overview',
        received: 'Received',
        given: 'Given',
        request: 'Requested',
        manager: 'Team Insights',
        hrOverview: 'HR Overview',
        bannerHeader: 'Help your colleagues improve. Start by providing feedback to them.',
        feedbackReceived: 'Feedback Received',
        positive: 'Positive',
        constructive: 'Constructive',
        giveFeedback: 'Give Feedback',
        reqFeedback: 'Request Feedback',
        seeFeedback: 'View Feedback',
        giveFeedbackText: 'Provide Feedback to your team either positive or constructive',
        reqFeedbackText: 'Request Feedback to your team either positive or constructive',
        createGoal: 'Create Goal',
        recentltReceived: 'Received',
        teamCompetency: 'Team Competency',
        seeAll: 'See All',
        teammaates: 'Teammates',
        exportFeedbackData: 'Export Feedback Data',
        projectOrTaskTitle: 'Project or Task Title',
        selectTeamMember: 'Select Team Member',
        giveNext: 'GiveNext',
        competency:"Select Competencies",
        date: 'Event Date',
        recognise: 'Recognise',
        ratePerson: 'How would you rate your team member in this area?',
        message: 'Message',
        thisWeek: 'This Week',
        thisMonth: 'This Month',
        last3Months: 'Last 3 Months',
        last6Months: 'Last 6 Months',
        last12Months:'Last 12 Months',
        doingGoodAt: 'Doing good at',
        improveOn: 'Need to improve on',
        peersRequest: 'Peers Request',
        yourRequest: 'Your Request',
        highPerformers: 'High Performers',
        needIntervention: 'Needs Intervention',
        viewMore: 'View More',
        export: 'Export',
        competencyHeatMap: 'Competency Heatmap',
        allMyCompetencies: 'All My Competencies',
        feedbackSummary: 'Feedback Summary',
        emptyOverviewPrimary: "Oops! You haven't got any feedback.",
        emptyOverviewSecondary: 'Start by requesting feedback from your peers and manager.',
        emptyReceivedPrimary: "Oops! You haven't got any feedback.",
        emptyReceivedSecondary: 'Start by requesting feedback from your peers and manager.',
        emptyGivenPrimary: 'You have not given any feedback yet.',
        emptyGivenSecondary: 'Would you like to start by giving feedback to your peers and manager?',
        emptyPeersPrimary: 'You have not received any feedback requests.',
        emptyYoursPrimary: 'You have not requested any feedback yet.',
        emptyYoursSecondary: 'Start by requesting feedback from your peers and manager.',
        emptyManagerPrimary: "Your team has not got any feedback for improvement.",
        emptyManagerSecondary: 'Please help them by giving them some feedback now.',
        selectCompetencyPH: "Select competency",
        eventPH: "Enter the title or name of the project",
        messagePH: "Type your message here...",
        warning: "Want to save your changes?",
        awesome: "Awesome!",
        feedbackBannerDescPrimary: "Constructive feedback helps your peers to improve and motivate. This week you have given ",
        // feedbackBannerDescSecondary: " feedback to your peers.",
        // feedbackBannerDescSecondary1: " feedbacks to your peers.",
        feedbackBannerDescSecondary: " feedback",
        feedbackBannerDescSecondary1: " feedbacks",
        reqFeedbackMsg: "requested your feedback",
        sentFeedbackMsg: "sent you a feedback",
        receivedFeedbackMsg: "received your feedback",
        receivedReqMsg: "received your request",
        eventError: "Title length should be less than 100 characters.",
        giveModalDatePH: "Select the date",
        reqModalPH: "Enter the date of project",
        anonymous: "Anonymous",
        anonymousFeedback: "sent you a feedback"
  
      },
      common: {
        close: "Close",
        signOut: "Sign Out",
        cancel: "Cancel",
        discardChanges: "Discard Changes",
        saveChanges: "Save Changes",
        search: "Search",
        confirm: "Confirm",
        upload: "Upload",
        save: "Save",
        ok: "OK",
        name: 'Name',
        address: 'Address',
        phone: 'Phone',
        email: 'Email',
        submit:"Submit",
        next: "Next",
        add: 'Add',
        dismiss: 'Dismiss',
        chat: 'Chat',
        settings: 'Settings'
      },
    },
    zh: {
      profile: {
        about: "关于", 
        badges: "徽章",
      },
    },
    de: {
      profile: {
        contact: "Kontakt",
        about: "über",
        badges: "Abzeichen",
        editProfile: "Profil bearbeiten",
        currentRank: "Aktueller Rang",
        lockedBadges: "Gesperrte Abzeichen",
        email: "E-Mail",
        personalEmail: "Persönliche E-Mail",
        contactNumber: "Kontakt Nummer",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        skype: "Skype",
        uploadPhoto: "Foto hochladen",
        editProfilePic: "Profilbild Speichern",
        uploadProfilePic: "+ Profilbild hochladen",
        max: "max",
        personalInfo: "Persönliche Informationen",
        nickname: "Spitzname",
        bio: "Bio",
        phoneNumber: "Telefonnummer",
      },
      notifications: {
        notifications: "Benachrichtigung",
        unread: "ungelesen",
        read: "lesen",
        markAllAsRead: "alles als gelesen markieren",
      },
      gigs: {
        gigs: "Gigs",
        availableGigs: "Verfügbar",
        acceptedGigs: "akzeptiert",
        ongoingGigs: "laufend",
        closedGigs: "geschlossen",
        createGig: "erstellen",
        newGig: "Neuer Gig",
        completedGigs: "beendet",
        updateGig: "aktualisieren",
        title: "Gig-Titel",
        description: "Beschreibung",
        skills: "Kompetenzen",
        gigType: "Gig-Typ",
        location: "Ort",
        startDate: "Anfangsdatum",
        startTime: "Startzeit",
        endDate: "Endtermin",
        endTime: "Endzeit",
        date: "Datum",
        gigInformation: 'Gig-Informationen',
        supervisor: 'Supervisor',
        assignedEngineer: 'Zugewiesener Ingenieur',
        email: 'E-Mail',
        timeline: 'Zeitleiste',
        feedback: 'Rückantwort'
      },
      locations: {
        locationList: "Standortliste",
        viewMap: "Ansichts Karte",
        createLocation: "Standort erstellen",
        updateLocation: "Standort aktualisieren",
        editLocation: "Standort bearbeiten",
        deleteLocation: "Standort löschen",
        locationDetails: 'Standortdetails',
        information: 'Information',
        contact: 'Kontakt',
        supervisor: 'Supervisor',
        engineersStationed: 'Stationierte Ingenieure',
        pastGigCompletion: 'Vergangene Gig-Fertigstellung',
        location: 'Ort'
      },
      people: {
        people: "Menschen",
        availableEngineers: "Verfügbare Ingenieure",
        leaves: "Abwesenheit"
      },
      home: {
        home: "Startseite",
        yourActivities: "Fortschritte in dieser Woche",
        thisWeek: 'In dieser Woche:',
        lastWeek: 'Letzte Woche:',
        userTrend: 'Seit letzter Woche',
        companyTrend: 'Unternehmenstrend',
        completed: 'beendet',
        earned: 'verdient',
        newQuest: "neue Suche",
        whatsNext: "Was kommt als nächstes",
        yourProfile: "Dein Profil",
        bannerHeader1: "Letzte Woche warst du in einer Serie, ",
        bannerDesc:"Letzte Woche hast du <b>{goalsCount}</b> Ziele und <b>{questsCount}</b> Quests abgeschlossen. Sie haben auch über <b>{pointsCount} Punkte </b>verdient. Lass es uns diese Woche besser machen.",
        bannerDescQuestAclOff:"Letzte Woche haben Sie <b>{goalsCount}</b> Ziele erreicht. Sie haben auch über <b>{pointsCount} Punkte </b>verdient. Lass es uns diese Woche besser machen.",
        bannerDescLeft1: "Letzte Woche haben Sie abgeschlossen",
        bannerDescMid1: "ziele und",
        bannerDescRight1: "quest.  Sie haben auch über verdient",
        bannerDescRightEnd1: "Lass es uns diese Woche besser machen",
        bannerHeader2: "herzlich willkommen ",
        bannerDesc2:
          "Ich hoffe, Sie werden für eine neue Woche der Produktivität erfrischt. Lassen Sie uns zunächst Ihre Ziele festlegen und Quests abschließen, um Punkte zu sammeln.",
        bannerDesc2QuestAclOff:
          "erfrischt. Lassen Sie uns zunächst Ihre Ziele festlegen, um Punkte zu sammeln.",
      },
      quest: {
        quests: 'Suchen',
        quest: "Aufgabe",
        ongoing: "laufend",
        completed: "beendet",
        moderator: "MODERATOR",
        points: "Punkte",
        done: "erledigt",
        status: "Status",
        submission: "Einreichung",
        reject: "ablehnen",
        approve: "genehmigen",
        badge: "Abzeichen",
        timeLeft: "Übrige Zeit",
        created: "erstellt",
        started: "Gestartet",
        emptyQuest: "Es ist noch keine Quest verfügbar",
        bannerHeader: "Steigern Sie sich, indem Sie Anerkennungspunkte sammeln. Hilf anderen, mit dir aufzustehen!",
        bannerDescLeft: "Erobere Quests und trete mit deinem Team an! Sie haben <b>",
        bannerDescMid: "</b> laufend",
      },
      leaderboard: {
        leaderboard: "Bestenliste",
        overall: "Insgesamt",
        team: "Mannschaft",
        bannerHeader: "Sammeln Sie Punkte und fordern Sie Ihre Kollegen heraus",
        bannerDesc:
          "Verfolgen Sie Ihre verdienten Punkte und sehen Sie, wo Sie unter Ihren Kollegen stehen. Fordern Sie sie für die",
        bannerDescRight: "Platz jede Woche",
        weekly: "wöchentlich",
        monthly: "monatlich",
        allTime: "alle Zeit",
        myStanding: "Mein Stehen",
        emptyPoints: "Es ist noch nichts verfügbar",
        previousWeek: "Previous Week",
      },
      myPoints: {
        rewardedBy: "belohnt von",
        badge: "Abzeichen",
        redemptionItem: "Einlösungsgegenstand",
        points: "Punkte",
        myPoints: "meine Punkte",
        currentPoints: "aktuelle Punkte",
        spent: "verbraucht",
        pending: "bevorstehend",
        totalPoints: "GESAMTPUNKTZAHL",
        type: "Art",
        awardedBy: "Verliehen",
        emptyPoints: "Sammeln Sie Punkte, um Belohnungen einzulösen und Erfolge zu erzielen"
      },
      redemption: {
        emptyHistoryRewards: "Es gibt noch keinen Artikel in Ihrer Geschichte",
        redemptionInfo: "Einlösungsinfo",
        description: "Beschreibung",
        redemption: "Erlösung",
        featured: "Hervorgehoben",
        history: "Geschichte",
        wishlist: "Wunschzettel",
        bannerHeader: "Belohnen Sie sich",
        bannerDesc:
          "Wir haben erstaunliche Gegenstände, die Sie mit Punkten einlösen können, die Sie durch das Erfüllen von Quests und Zielen verdienen.",
        categories: "Kategorien",
        seeAll: "alles sehen",
        emptyRewards: "Es gibt noch keine Belohnungen",
        justForYou: "Nur für dich",
        topRewards: "Top Belohnungen",
        redemptionInfo: "Redemption Info", // german translation is missing
        status: "Status",
        expiringOn: "Abläuft am",
        Redeem: "einlösen",
        emptyWishlistRewards: "Ihre Wunschliste enthält noch keine Artikel",
      },
      approveGoal: {
        alertTitle: "Ziel genehmigen",
        alertbody: "Bestätigen Sie den Abschluss von",
        goal: "Tor",
        approve: "genehmigen",
      },
      completeGoal: {
        alertTitle: "VOLLSTÄNDIGES ZIEL",
        alertbody: "Sind Sie sicher, dass Sie dieses Ziel erreichen möchten?",
        submit: "einreichen",
      },
      deleteGoal: {
        alertTitle: "Ziel löschen",
        alertbody: "Sind Sie sicher, dass Sie dieses Ziel löschen möchten?",
        delete: "löschen",
      },
      rejectGoal: {
        alertTitle: "Ziel ablehnen",
        alertbodyleft: "Irgendwas stimmt nicht",
        alertbodyright: "Ziel? Was ist der Grund?",
        reject: "ablehnen",
      },
      submitGoal: {
        alertTitle: "Ziel senden",
        alertbody:
          "Wenn Sie dieses Ziel einreichen, werden alle Aufgaben abgeschlossen und zur Überprüfung durch eingereicht.",
        submit: "einreichen",
      },
      lazyLoading: {
        suspense: "Ich arbeite daran ...",
      },
      logoutDialog: {
        modalTitle: "Wir werden dich vermissen",
        modalBody: "Sind Sie sicher, dass Sie fortfahren möchten?",
        modalFooter: "geh zurück",
        continue: "Fortsetzen",
      },
      sideNavBar: {
        logoText: "SelfDrvn",
        admin: "Verwalter",
        goalSetting: "Ziele",
        reward: "Belohnung",
        locations: "Standorte",
        gigs: "Gigs",
        people: "Menschen",
        quest: "Suchen",
        quiz: "Ratespiel",
        organization: "Organisation",
        info: "Information",
        rmDashboard: "Instrumententafel",
        GigArenaHeader: "GigArena"
      },
      notFound: {
        topText: "Diese Seite existiert nicht.",
        bottomText:
          "Wir haben überall nach dieser Seite gesucht. Sind Sie sicher, dass die URL der Website korrekt ist? Wenden Sie sich an unser Support-Team, um Hilfe zu erhalten.",
      },
      goalSetting: {
        goals: 'Ziele',
        goalSetting: "Zielsetzung",
        yourGoals: "Deine ziele",
        editGoal: "Ziel bearbeitenl",
        newGoal: "Neues Ziel",
        targeting: "Was ist das Hauptergebnis, auf das Sie abzielen?",
        goalAlignment: "Zielausrichtung",
        addTask: "Aufgabe hinzufügen",
        reviewee: "Rezension",
        maxDateMessage: 'Das Datum für "erkennen mich daran" sollte nicht nach dem Fälligkeitsdatum liegen',
        task: "Aufgabe",
        taskName: "Aufgabennname",
        deleteTheTask: "Löschen Sie die Aufgabe",
        dueDate: "Geburtstermin",
        remindMe: "Erinnere mich (optional)",
        strin: "strin",    //missing de translation for this
        updateGoal: "Zielaktualisierung",
        startGoal: "Ziel starten",
        emptyGoals:
          "Es gibt noch keine Ziele. Sie können beginnen, indem Sie jetzt ein Ziel hinzufügen.",
        deleteGoal: "Ziel löschen",
        reviewer: "Rezensent",
        reject: "ablehnen",
        approve: "genehmigen",
        sGoal: "Ziel",
        selectGoalAlignments: "Wählen Sie Zielausrichtungen",
        teamGoals: "Teamziel",
        bannerHeader: "Bewegen Sie sich als Team vorwärts in Richtung Unternehmensziele",
        bannerDesc: "Jedes Ziel soll Ihnen und Ihrem Unternehmen helfen, zusammen zu wachsen. Schließe so viele wie möglich ab.",
        hasNotStarted: "hat nicht begonnen",
        ongoing: "laufend",
        pendingReview: "ausstehende Bewertung",
        completed: "beendet",
        submitForReview: "zur Überprüfung einreichen",
        completeGoal: "VOLLSTÄNDIGES ZIEL",
        noGoals: "Keine Ziele",
        goalStatus: "Zielstatus",
        addNewGoal: "Neues Ziel hinzufügen",
        teamMembers: "Teammitglieder",
        selectReviewee: "Wählen Sie Reviewee",
        selectReviewer: "Wählen Sie Reviewer",
        goalNotFound: "Ziel nicht gefunden.",
        goalOwner: "Ziel Besitzer",
      },
      rmDashboard : {
        overViewTab: "Überblick",
        LeaveTab: "Blätter",
        ExportDataButton: "Daten exportieren",
        CurrentDayAction: "Aktuelle Tagesaktionen",
        EngineersOnLeave: "Ingenieure beurlaubt",
        EngineersWhoAreLate: "Ingenieure, die zu spät kommen",
        ListOfGigsOpenToday: "Liste der heute geöffneten Gigs",
        ListOfAvailableReplacementEngineers: "Liste der verfügbaren Ersatzingenieure",
        ListOfEngineersAppliedLeaveForNext5Days: "Liste der Ingenieure, die Urlaub für die nächsten 5 Tage beantragt haben", 
      },
      quiz: {
        bannerHeader: "Ratespiel",
        all: "alle zusammen",
        ongoing: "laufend",
        expired: "abgelaufen",
        completed: "beendet",
        published:"veröffentlicht",
        drafts: "Entwürfe",
        admin: "Verwalter",
        user:"Benutzer",
        quiz:"Ratespiel",
        quizes:"Quiz",
        addNewQuiz:"Neues Quiz hinzufügen",
        republishQuiz:"Quiz erneut veröffentlichen",
        republish: "Neu veröffentlichen",
        exportData:"Daten exportieren",
        admin: "Admin",
        timeLeft: "Übrige Zeit",
        edit:"bearbeiten",
        unpublishQuiz:"Unpublish Quiz",
        addParticipants:"Teilnehmer hinzufügen",
        export:"exportieren",
        shareLink:"eine verknüpfung teilen",
        publishedResponses: "Wie gut kennen Sie Ihr Unternehmen?",
        users:"Benutzer",
        sentOn:"senden an",
        responded:"Antwortete",
        pending:"bevorstehend",
        score:"Punktzahl",
        hasNotResponded:"Hat nicht geantwortet",
        title: "Ratespiletitel",
        titlePlaceholder:"Geben Sie hier den Quiztitel ein",
        description:"Beschreibung",
        descriptionPlaceHolder:"Geben Sie hier die Quizbeschreibung ein",
        quit:"aufhören",
        publish:"veröffentlichen",
        saveAsDraft:"als Entwurf speichern",
        details:"Einzelheiten",
        settings:"Frageneinstellungen",
        switch:"Willkürlich Optionen bestellen",
        randomize:"Willkürlich Antworten bestellen",
        question:"Frage",
        score:"Score  ", //missing de translation
        scoreInfo:"Bitte assign Punktzahl nach der Schwierigkeit der Frage",
        multipleChoice:"Mehrfachauswahl",
        singleChoice:"Eine Wahl",
        nextQuestion:" + Nächste Frage",
        remove:"entfernen",
        rightAnswerInfo:"Fügen Sie den richtigen Antworttext hinzu",
        wrongAnswerInfo:"Falschen Antworttext hinzufügen",
        addOption: "+ Option hinzufügen",
        questionGraphic: "Frage Grafik",
        addQuestionGraphic:"Frage Grafik hinzufügen",
        quizMe: "Quiz mich!",
        completedQuiz: "Abgeschlossen - Siehe Ergebnis",
        ongoigQuizAnswered: "Leute haben dieses Quiz bereits abgeschlossen",
        completedQuizAnswered: "Leute haben dieses Quiz bereits beantwortet",
        expiredQuizAnswered: "Sie haben auf dieses Quiz nicht geantwortet",
        isCorrectMsg:"Gut gemacht!",
        wrongAnswerMsg: "Das ist nicht richtig. Mach dir keine Sorgen, du wirst es beim nächsten Versuch bekommen.",
        submitQuiz:"Quiz absenden",
        selectMoreText:"Wählen Sie mehr als eine Antwort",
        // question: "Question",
        confirm: "bestätigen",
        confirmText: "Bist du sicher?",
        confirmSubtext: "Sie können dieses Quiz nicht wiederholen, nachdem Sie die Antworten angezeigt haben",
        confirmSubheader: "Möchten Sie die Seite wirklich verlassen?",
        discardText: "Möchten Sie das Quiz wirklich verwerfen?",
        publishEditText: "Sind Sie sicher, dass Sie fortfahren möchten?",
        publishEditSubtext: "Das Quiz wäre nicht zur Verfügung und die Benutzer Antwort zurückgesetzt",
        publishDescForUnavailable: "The users response will be reset",
        days: "TAGE",
        youCompleted: "Sie haben abgeschlossen",
        attemptsLeft: "Versuche übrig",
        retakeQuiz: "wiederholen Sie das Ratespiel",
        viewAnswers: "Antwort anzeigen",
        quizInvitation: "Quiz Einladung",
        respondents: "die Befragten",
        subject: "Gegenstand",
        message: "Botschaft",
        publishDate: "Veröffentlichungsdatum",
        expiryDate: "Verfallsdatum",
        optional: "optional",
        remindUsersBy: "Erinnern Sie Benutzer durch",
        numberOfAttempts: "Anzahl der Versuche",
        addNewQuest: "Zu einer neuen Quest hinzufügen",
        back: "zurück",
        quizInvitationInfo:"Erstellt mit diesem Quiz eine neue Quest als eine der Questaktione",
        dateText: "Datum ist gemäß GMT + 8",
        daysSubmission: "Tage vor der Einreichung",
        selectQuizToRepublish:"Wählen Sie das Quiz aus, um es erneut zu veröffentlichen",
        everyone: "jeder",
        yes:"ja",
        remindLabel: "Days remaning until due date", //Missing german translation
        unlimitedAttemptsLabel: "0 = unlimited attempts", //Missing german translation
        dateRangeText: "Apply", //Missing german translation
        quizBannerDesc:
        "Taking a quiz tests your understanding, helps you retain the info you already have, and identifies gaps in your knowledge so you can get more help where needed. What's more - they're fun! So go ahead and give it a go!", //Missing german translation
      },
      common: {
        close: "schließen",
        signOut: "ausloggen",
        cancel: "stornieren",
        discardChanges: "Änderungen verwerfen",
        saveChanges: "Änderungen speichern",
        search: "suchen",
        confirm: "bestätigen",
        upload: "hochladen",
        save: "speichern",
        ok: "in Ordnung",
        name: 'Name',
        address: 'Adresse',
        phone: 'Telefon',
        email: 'E-Mail',
        submit:"einreichen"
      },
    }
  };
  
  export { localizedStrings };
  