let myId=1130

let a={
    "OneTime": [
        {
            "Id": "1451505",
            "QuestId": "992",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "attachment upload quest",
            "Description": "-",
            "StartDate": "2022-01-09 18:30:00",
            "EndDate": "2999-12-31 18:29:00",
            "BadgeCode": "",
            "BadgeName": "",
            "BadgeImageUrl": "",
            "Point": 9,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2315435",
                    "QuestActivityId": null,
                    "Description": "none",
                    "Value": "1",
                    "RedirectionType": "ModeratorQuest",
                    "SpecificQuestId": "791",
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": true,
                    "ModeratorId": "428",
                    "ModeratorName": "pushyami nagella",
                    "ModeratorImageUrl": "https://selfdrvnqat.blob.core.windows.net/selfdrvnqat/31177b2a-e744-4bf9-b6d7-27fa4f9724f2/users/428/44968698-8196-45be-840a-a6ff3f6b5760.jpeg",
                    "ModeratorEmail": "pushyami@selfdrvn.com",
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": "",
                    "ModeratorPosition": "Administrator",
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "25",
            "CategoryName": "Milestone",
            "CreatedDate": "2022-04-05 03:16:55",
            "Skills": [
                {
                    "Id": 5,
                    "Name": "ios"
                }
            ]
        },
        {
            "Id": "1451504",
            "QuestId": "1051",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "no expiry quest",
            "Description": "desc",
            "StartDate": "2022-02-15 18:30:00",
            "EndDate": "2999-12-31 18:29:00",
            "BadgeCode": "quarter",
            "BadgeName": "Quarter",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10585/0b376ba9-1ea5-4ad7-bd2e-c5c7dc2c57b8.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2315434",
                    "QuestActivityId": null,
                    "Description": "Add a profile picture",
                    "Value": "1",
                    "RedirectionType": "Profile",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "22",
            "CategoryName": "Collaboration",
            "CreatedDate": "2022-04-05 03:16:55",
            "Skills": [
                {
                    "Id": 3,
                    "Name": ".net"
                }
            ]
        },
        {
            "Id": "1451503",
            "QuestId": "1074",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "No expiry",
            "Description": "desc",
            "StartDate": "2022-02-22 18:30:00",
            "EndDate": "2999-12-31 18:29:00",
            "BadgeCode": "bakersdozen",
            "BadgeName": "Bakers Dozen",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10585/606d8e46-077f-470e-8e46-11ae4e7b8cae.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2315433",
                    "QuestActivityId": null,
                    "Description": "Add a profile picture",
                    "Value": "1",
                    "RedirectionType": "Profile",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "22",
            "CategoryName": "Collaboration",
            "CreatedDate": "2022-04-05 03:16:54",
            "Skills": [
                {
                    "Id": 9,
                    "Name": ".net test"
                }
            ]
        },
        {
            "Id": "1455211",
            "QuestId": "1130",
            "Status": "Claimed",
            "StatusId": "4",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "FINAL-QUEST",
            "Description": "FINAL-QUEST-DESCRIPTION",
            "StartDate": "2022-04-04 18:30:00",
            "EndDate": "2022-04-16 18:29:00",
            "BadgeCode": "cyberstar",
            "BadgeName": "Cyberstar",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10546/5f1ff19a-82fc-4aa3-a73c-39aede1b8909.png",
            "Point": 1000,
            "Conditions": [
                {
                    "TrackingValue": "1",
                    "Completed": true,
                    "Id": "2319241",
                    "QuestActivityId": null,
                    "Description": "Like a post",
                    "Value": "1",
                    "RedirectionType": "Feed",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": true,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "23",
            "CategoryName": "Feedback",
            "CreatedDate": "2022-04-10 22:08:20",
            "Skills": [
                {
                    "Id": 4,
                    "Name": "Android"
                },
                {
                    "Id": 5,
                    "Name": "ios"
                }
            ]
        },
        {
            "Id": "1455241",
            "QuestId": "1135",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "Quest-1",
            "Description": "QUEST-DESCRIPTION",
            "StartDate": "2022-04-10 18:30:00",
            "EndDate": "2022-04-14 18:29:00",
            "BadgeCode": "",
            "BadgeName": "",
            "BadgeImageUrl": "",
            "Point": 10000,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2319271",
                    "QuestActivityId": null,
                    "Description": "Like 1000 posts",
                    "Value": "1000",
                    "RedirectionType": "Feed",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "23",
            "CategoryName": "Feedback",
            "CreatedDate": "2022-04-10 22:25:30",
            "Skills": [
                {
                    "Id": 35,
                    "Name": "H"
                },
                {
                    "Id": 9,
                    "Name": ".net test"
                }
            ]
        }
    ],
    "Daily": [],
    "DailyDueDate": "",
    "Weekly": [],
    "WeeklyDueDate": "",
    "Monthly": [
        {
            "Id": "1448921",
            "QuestId": "1044",
            "Status": "Claimed",
            "StatusId": "4",
            "RecurrenceType": "Monthly",
            "RecurrenceTypeId": "3",
            "Name": "mnth qwe",
            "Description": "ftgj",
            "StartDate": "2022-03-31 18:30:00",
            "EndDate": "2022-04-30 18:29:00",
            "BadgeCode": "kdrbadge",
            "BadgeName": "KDR BADGE",
            "BadgeImageUrl": "https://selfdrvn-qat-cdn.azureedge.net/selfdrvnqat/31177b2a-e744-4bf9-b6d7-27fa4f9724f2/badge/a72f522a-ebf8-4f47-939a-16367c2a0cd1.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "1",
                    "Completed": true,
                    "Id": "2312639",
                    "QuestActivityId": null,
                    "Description": "Like a post",
                    "Value": "1",
                    "RedirectionType": "Feed",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": true,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "24",
            "CategoryName": "Learning",
            "CreatedDate": "2022-03-31 12:59:23",
            "Skills": [
                {
                    "Id": 4,
                    "Name": "Android"
                }
            ]
        },
        {
            "Id": "1448918",
            "QuestId": "1053",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Monthly",
            "RecurrenceTypeId": "3",
            "Name": "occur monthly quest",
            "Description": "desc",
            "StartDate": "2022-03-31 18:30:00",
            "EndDate": "2022-04-30 18:29:00",
            "BadgeCode": "quarter",
            "BadgeName": "Quarter",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10585/0b376ba9-1ea5-4ad7-bd2e-c5c7dc2c57b8.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2312636",
                    "QuestActivityId": null,
                    "Description": "Add a profile picture",
                    "Value": "1",
                    "RedirectionType": "Profile",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "22",
            "CategoryName": "Collaboration",
            "CreatedDate": "2022-03-31 12:59:23",
            "Skills": [
                {
                    "Id": 7,
                    "Name": "css"
                }
            ]
        }
    ],
    "MonthlyDueDate": "2022-04-30 18:29:00",
    "Completed": [],
    "Incomplete": [
        {
            "Id": "1455241",
            "QuestId": "1135",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "Quest-1",
            "Description": "QUEST-DESCRIPTION",
            "StartDate": "2022-04-10 18:30:00",
            "EndDate": "2022-04-14 18:29:00",
            "BadgeCode": "",
            "BadgeName": "",
            "BadgeImageUrl": "",
            "Point": 10000,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2319271",
                    "QuestActivityId": null,
                    "Description": "Like 1000 posts",
                    "Value": "1000",
                    "RedirectionType": "Feed",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "23",
            "CategoryName": "Feedback",
            "CreatedDate": "2022-04-10 22:25:30",
            "Skills": [
                {
                    "Id": 35,
                    "Name": "H"
                },
                {
                    "Id": 9,
                    "Name": ".net test"
                }
            ]
        },
        {
            "Id": "1448918",
            "QuestId": "1053",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Monthly",
            "RecurrenceTypeId": "3",
            "Name": "occur monthly quest",
            "Description": "desc",
            "StartDate": "2022-03-31 18:30:00",
            "EndDate": "2022-04-30 18:29:00",
            "BadgeCode": "quarter",
            "BadgeName": "Quarter",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10585/0b376ba9-1ea5-4ad7-bd2e-c5c7dc2c57b8.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2312636",
                    "QuestActivityId": null,
                    "Description": "Add a profile picture",
                    "Value": "1",
                    "RedirectionType": "Profile",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "22",
            "CategoryName": "Collaboration",
            "CreatedDate": "2022-03-31 12:59:23",
            "Skills": [
                {
                    "Id": 7,
                    "Name": "css"
                }
            ]
        },
        {
            "Id": "1451505",
            "QuestId": "992",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "attachment upload quest",
            "Description": "-",
            "StartDate": "2022-01-09 18:30:00",
            "EndDate": "2999-12-31 18:29:00",
            "BadgeCode": "",
            "BadgeName": "",
            "BadgeImageUrl": "",
            "Point": 9,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2315435",
                    "QuestActivityId": null,
                    "Description": "none",
                    "Value": "1",
                    "RedirectionType": "ModeratorQuest",
                    "SpecificQuestId": "791",
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": true,
                    "ModeratorId": "428",
                    "ModeratorName": "pushyami nagella",
                    "ModeratorImageUrl": "https://selfdrvnqat.blob.core.windows.net/selfdrvnqat/31177b2a-e744-4bf9-b6d7-27fa4f9724f2/users/428/44968698-8196-45be-840a-a6ff3f6b5760.jpeg",
                    "ModeratorEmail": "pushyami@selfdrvn.com",
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": "",
                    "ModeratorPosition": "Administrator",
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "25",
            "CategoryName": "Milestone",
            "CreatedDate": "2022-04-05 03:16:55",
            "Skills": [
                {
                    "Id": 5,
                    "Name": "ios"
                }
            ]
        },
        {
            "Id": "1451503",
            "QuestId": "1074",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "No expiry",
            "Description": "desc",
            "StartDate": "2022-02-22 18:30:00",
            "EndDate": "2999-12-31 18:29:00",
            "BadgeCode": "bakersdozen",
            "BadgeName": "Bakers Dozen",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10585/606d8e46-077f-470e-8e46-11ae4e7b8cae.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2315433",
                    "QuestActivityId": null,
                    "Description": "Add a profile picture",
                    "Value": "1",
                    "RedirectionType": "Profile",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "22",
            "CategoryName": "Collaboration",
            "CreatedDate": "2022-04-05 03:16:54",
            "Skills": [
                {
                    "Id": 9,
                    "Name": ".net test"
                }
            ]
        },
        {
            "Id": "1451504",
            "QuestId": "1051",
            "Status": "New",
            "StatusId": "0",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "no expiry quest",
            "Description": "desc",
            "StartDate": "2022-02-15 18:30:00",
            "EndDate": "2999-12-31 18:29:00",
            "BadgeCode": "quarter",
            "BadgeName": "Quarter",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10585/0b376ba9-1ea5-4ad7-bd2e-c5c7dc2c57b8.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "0",
                    "Completed": false,
                    "Id": "2315434",
                    "QuestActivityId": null,
                    "Description": "Add a profile picture",
                    "Value": "1",
                    "RedirectionType": "Profile",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": false,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "22",
            "CategoryName": "Collaboration",
            "CreatedDate": "2022-04-05 03:16:55",
            "Skills": [
                {
                    "Id": 3,
                    "Name": ".net"
                }
            ]
        }
    ],
    "Claimed": [
        {
            "Id": "1455211",
            "QuestId": "1130",
            "Status": "Claimed",
            "StatusId": "4",
            "RecurrenceType": "Onetime",
            "RecurrenceTypeId": "0",
            "Name": "FINAL-QUEST",
            "Description": "FINAL-QUEST-DESCRIPTION",
            "StartDate": "2022-04-04 18:30:00",
            "EndDate": "2022-04-16 18:29:00",
            "BadgeCode": "cyberstar",
            "BadgeName": "Cyberstar",
            "BadgeImageUrl": "https://atasproduction.blob.core.windows.net/feeds/10546/5f1ff19a-82fc-4aa3-a73c-39aede1b8909.png",
            "Point": 1000,
            "Conditions": [
                {
                    "TrackingValue": "1",
                    "Completed": true,
                    "Id": "2319241",
                    "QuestActivityId": null,
                    "Description": "Like a post",
                    "Value": "1",
                    "RedirectionType": "Feed",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": true,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "23",
            "CategoryName": "Feedback",
            "CreatedDate": "2022-04-10 22:08:20",
            "Skills": [
                {
                    "Id": 4,
                    "Name": "Android"
                },
                {
                    "Id": 5,
                    "Name": "ios"
                }
            ]
        },
        {
            "Id": "1448921",
            "QuestId": "1044",
            "Status": "Claimed",
            "StatusId": "4",
            "RecurrenceType": "Monthly",
            "RecurrenceTypeId": "3",
            "Name": "mnth qwe",
            "Description": "ftgj",
            "StartDate": "2022-03-31 18:30:00",
            "EndDate": "2022-04-30 18:29:00",
            "BadgeCode": "kdrbadge",
            "BadgeName": "KDR BADGE",
            "BadgeImageUrl": "https://selfdrvn-qat-cdn.azureedge.net/selfdrvnqat/31177b2a-e744-4bf9-b6d7-27fa4f9724f2/badge/a72f522a-ebf8-4f47-939a-16367c2a0cd1.png",
            "Point": 0,
            "Conditions": [
                {
                    "TrackingValue": "1",
                    "Completed": true,
                    "Id": "2312639",
                    "QuestActivityId": null,
                    "Description": "Like a post",
                    "Value": "1",
                    "RedirectionType": "Feed",
                    "SpecificQuestId": null,
                    "SpecificQuestActivityName": null,
                    "PopUpType": null,
                    "AdditionalParam": null,
                    "Status": "SUBMIT",
                    "isModeratorQuest": false,
                    "ModeratorId": null,
                    "ModeratorName": null,
                    "ModeratorImageUrl": null,
                    "ModeratorEmail": null,
                    "IsModeratorExcluded": false,
                    "Title": null,
                    "Url": null,
                    "IsDocumentRequired": false,
                    "TipText": null,
                    "ModeratorPosition": null,
                    "ModeratorRemarks": null,
                    "ModeratorCommentedOn": null
                }
            ],
            "Completed": true,
            "UpdatedDate": null,
            "HasNoExpireDate": false,
            "StreakQuest": false,
            "StreakPoint": 0,
            "StreakDuration": 0,
            "QuestCategoryId": "24",
            "CategoryName": "Learning",
            "CreatedDate": "2022-03-31 12:59:23",
            "Skills": [
                {
                    "Id": 4,
                    "Name": "Android"
                }
            ]
        }
    ],
    "CurrentDateTime": "2022-04-11 07:50:20"
}

const finalResult=(a.Claimed).filter(obj=>{
    return obj.QuestId
})

// console.log(a.Claimed[0].QuestId);
// console.log(a.Claimed);
console.log(finalResult);